enum AppLanguage { en, te }

extension AppLanguageX on AppLanguage {
  String get code => this == AppLanguage.te ? 'te' : 'en';
}

class AppLocalizations {
  const AppLocalizations._();

  static const Map<String, String> _en = {
    'app_name': 'Babai Bazor',
    'app_name_te': 'బాబాయ్ బజార్',
    'tagline': 'Fresh Groceries Delivered',
    'tagline_te': 'తాజా కూరగాయలు ఇంటికి',
    'slide2_title': 'Fast Delivery',
    'slide2_subtitle': 'Get groceries to your door in minutes',
    'slide3_title': 'Daily Savings',
    'slide3_subtitle': 'Best prices on fresh daily essentials',
    'next': 'Next',
    'get_started': 'Get Started',
    'choose_language': 'Choose Language',
    'choose_language_te': 'భాష ఎంచుకోండి',
    'english_desc': 'English interface',
    'telugu_desc': 'Telugu interface',
    'continue': 'Continue',
    'continue_te': 'కొనసాగించు',
    'change_anytime': 'Change anytime in Settings',
    'change_anytime_te': 'సెట్టింగ్స్ లో ఎప్పుడైనా మార్చండి',
    'login_welcome_title': 'Welcome to Babai Bazaar',
    'welcome': 'Welcome!',
    'welcome_te': 'స్వాగతం!',
    'mobile_number': 'Mobile Number',
    'mobile_number_te': 'మొబైల్ నంబర్',
    'get_otp': 'Get OTP',
    'get_otp_te': 'OTP పొందండి',
    'no_password': 'No password · OTP only',
    'continue_as_guest': 'Continue as Guest',
    'skip': 'Skip',
    'no_password_te': 'పాస్‌వర్డ్ అవసరం లేదు · OTP మాత్రమే',
    'verify_otp': 'Verify OTP',
    'verify_otp_te': 'OTP ధృవీకరించండి',
    'sent_to': 'Sent to',
    'change_number': 'Change number?',
    'change_number_te': 'నంబర్ మార్చాలా?',
    'expires_in': 'Expires in',
    'resend_otp': 'Resend OTP',
    'verify': 'Verify',
    'verify_te': 'ధృవీకరించు',
    'or': 'or',
    'ten_minutes': '10 minutes valid',
    'ten_minutes_te': '10 నిమిషాలు చెల్లుతుంది',
    'otp_verified': 'OTP verified successfully',
    'otp_verified_te': 'OTP విజయవంతంగా ధృవీకరించబడింది',
    'home_coming': 'Home screen will be added next.',
    'invalid_mobile': 'Enter a valid 10-digit mobile number.',
    'invalid_otp': 'Enter a valid 4-digit OTP.',
    'resend_done': 'OTP resent successfully.',
    'select_location': 'Select Location',
    'delivery_area_label': 'Delivery Area',
    'delivery_area_hint': 'Enter your full area manually or use auto fetch.',
    'delivery_area_placeholder': 'Street, area, landmark, city, pincode',
    'auto_fetch_location': 'Auto Fetch Current Location',
    'continue_to_login': 'Continue to Login',
    'location_service_disabled': 'Location service is turned off.',
    'location_permission_denied': 'Location permission denied.',
    'location_fetch_failed': 'Could not fetch your location right now.',
    'location_not_found': 'Address not found for your current location.',
    'location_not_serviceable': 'Delivery is not available for this pincode.',
    'enter_delivery_area': 'Please enter your delivery area.',
    'type_4_chars_hint': 'Type at least 4 characters to view suggestions.',
    'suggested_areas': 'Suggested areas',
    'sending_otp': 'Sending OTP...',
    'error_title': 'Something went wrong',
    'ok': 'OK',
    'network_error': 'No internet connection. Please check and try again.',
    'request_timeout': 'Request timed out. Please try again.',
    'send_otp_failed': 'Could not send OTP. Please try again.',
    'unexpected_error': 'Unexpected error occurred. Please try again.',
    'verifying_otp': 'Verifying OTP...',
    'verify_otp_failed': 'Could not verify OTP. Please try again.',
    'otp_verified_for': 'Mobile verified for',
    'login_welcome_to': 'Welcome to',
    'login_or_signup_continue': 'Login or signup to continue',
    'enter_mobile_number': 'Enter your mobile number',
    'login_otp_hint': 'We\'ll send an OTP to verify your number',
    'or_continue_with': 'or continue with',
    'continue_with_google': 'Continue with Google',
    'choose_language_inline': 'Choose language',
    'google_login_soon': 'Google login coming soon.',
    'english': 'English',
    'telugu': 'తెలుగు',
    'request_completed': 'Request completed.',
    'guest': 'Guest',
    'done': 'Done',
    'profile_title': 'My Profile',
    'profile_customer_profile': 'Customer Profile',
    'profile_profile_details': 'Profile Details',
    'profile_saved_addresses': 'Saved Addresses',
    'profile_no_saved_addresses':
        'No saved addresses yet. Tap Add to create one.',
    'profile_address_fallback': 'Address',
    'profile_pin_prefix': 'PIN',
    'profile_default': 'Default',
    'profile_name': 'Name',
    'profile_mobile': 'Mobile',
    'profile_village': 'Village',
    'profile_pincode': 'Pincode',
    'profile_add': 'Add',
    'profile_edit_profile': 'Edit Profile',
    'profile_delete': 'Delete',
    'profile_cancel': 'Cancel',
    'profile_update': 'Update',
    'profile_add_address': 'Add Address',
    'profile_delete_address': 'Delete Address',
    'profile_delete_confirm': 'Are you sure you want to delete',
    'profile_updated_success': 'Profile updated successfully',
    'profile_address_added_success': 'Address added successfully',
    'profile_address_deleted': 'Address deleted',
  };

  static const Map<String, String> _te = {
    'app_name': 'బాబాయ్ బజార్',
    'app_name_te': 'Babai Bazor',
    'tagline': 'తాజా కూరగాయలు ఇంటికి',
    'tagline_te': 'Fresh Groceries Delivered',
    'slide2_title': 'వేగవంతమైన డెలివరీ',
    'slide2_subtitle': 'కొన్ని నిమిషాల్లో మీ ఇంటికి సరుకులు',
    'slide3_title': 'ప్రతిరోజు ఆదా',
    'slide3_subtitle': 'రోజువారీ అవసరాలపై ఉత్తమ ధరలు',
    'next': 'తర్వాత',
    'get_started': 'ప్రారంభించండి',
    'choose_language': 'భాష ఎంచుకోండి',
    'choose_language_te': 'Choose Language',
    'english_desc': 'English interface',
    'telugu_desc': 'Telugu interface',
    'continue': 'కొనసాగించు',
    'continue_te': 'Continue',
    'change_anytime': 'సెట్టింగ్స్ లో ఎప్పుడైనా మార్చండి',
    'change_anytime_te': 'Change anytime in Settings',
    'login_welcome_title': 'బాబాయ్ బజార్‌కు స్వాగతం',
    'welcome': 'స్వాగతం!',
    'welcome_te': 'Welcome!',
    'mobile_number': 'మొబైల్ నంబర్',
    'mobile_number_te': 'Mobile Number',
    'get_otp': 'OTP పొందండి',
    'get_otp_te': 'Get OTP',
    'no_password': 'పాస్‌వర్డ్ అవసరం లేదు · OTP మాత్రమే',
    'continue_as_guest': 'అతిథిగా కొనసాగండి',
    'skip': 'స్కిప్',
    'no_password_te': 'No password · OTP only',
    'verify_otp': 'OTP ధృవీకరించండి',
    'verify_otp_te': 'Verify OTP',
    'sent_to': 'కు పంపబడింది',
    'change_number': 'నంబర్ మార్చాలా?',
    'change_number_te': 'Change number?',
    'expires_in': 'మిగిలిన సమయం',
    'resend_otp': 'OTP మళ్లీ పంపండి',
    'verify': 'ధృవీకరించు',
    'verify_te': 'Verify',
    'or': 'లేదా',
    'ten_minutes': '10 నిమిషాలు చెల్లుతుంది',
    'ten_minutes_te': '10 minutes valid',
    'otp_verified': 'OTP విజయవంతంగా ధృవీకరించబడింది',
    'otp_verified_te': 'OTP verified successfully',
    'home_coming': 'హోమ్ స్క్రీన్ తర్వాత జోడిస్తాం.',
    'invalid_mobile': 'సరైన 10 అంకెల మొబైల్ నంబర్ ఇవ్వండి.',
    'invalid_otp': 'సరైన 4 అంకెల OTP ఇవ్వండి.',
    'resend_done': 'OTP మళ్లీ పంపబడింది.',
    'select_location': 'లొకేషన్ ఎంచుకోండి',
    'delivery_area_label': 'డెలివరీ ఏరియా',
    'delivery_area_hint':
        'మీ పూర్తి ఏరియాను మాన్యువల్ గా ఇవ్వండి లేదా ఆటో ఫెచ్ వాడండి.',
    'delivery_area_placeholder': 'వీధి, ఏరియా, ల్యాండ్‌మార్క్, నగరం, పిన్‌కోడ్',
    'auto_fetch_location': 'ప్రస్తుత లొకేషన్ ఆటో ఫెచ్',
    'continue_to_login': 'లాగిన్ కు కొనసాగండి',
    'location_service_disabled': 'లొకేషన్ సర్వీస్ ఆఫ్ లో ఉంది.',
    'location_permission_denied': 'లొకేషన్ అనుమతి నిరాకరించబడింది.',
    'location_fetch_failed': 'ఇప్పుడు మీ లొకేషన్ తీసుకురాలేకపోయాము.',
    'location_not_found': 'ప్రస్తుత లొకేషన్ కు అడ్రస్ దొరకలేదు.',
    'location_not_serviceable': 'ఈ పిన్‌కోడ్‌కు డెలివరీ అందుబాటులో లేదు.',
    'enter_delivery_area': 'దయచేసి మీ డెలివరీ ఏరియా నమోదు చేయండి.',
    'type_4_chars_hint': 'సజెషన్లు చూడటానికి కనీసం 4 అక్షరాలు టైప్ చేయండి.',
    'suggested_areas': 'సజెస్ట్ చేసిన ఏరియాలు',
    'sending_otp': 'OTP పంపిస్తున్నాం...',
    'error_title': 'ఏదో పొరపాటు జరిగింది',
    'ok': 'సరే',
    'network_error': 'ఇంటర్నెట్ కనెక్షన్ లేదు. మళ్లీ ప్రయత్నించండి.',
    'request_timeout': 'రిక్వెస్ట్ టైమ్ అవుట్ అయింది. మళ్లీ ప్రయత్నించండి.',
    'send_otp_failed': 'OTP పంపలేకపోయాం. మళ్లీ ప్రయత్నించండి.',
    'unexpected_error': 'అనుకోని లోపం వచ్చింది. మళ్లీ ప్రయత్నించండి.',
    'verifying_otp': 'OTP ధృవీకరిస్తున్నాం...',
    'verify_otp_failed': 'OTP ధృవీకరించలేకపోయాం. మళ్లీ ప్రయత్నించండి.',
    'otp_verified_for': 'ఈ మొబైల్ ధృవీకరించబడింది',
    'login_welcome_to': 'స్వాగతం',
    'login_or_signup_continue': 'కొనసాగడానికి లాగిన్ లేదా సైన్ అప్ చేయండి',
    'enter_mobile_number': 'మీ మొబైల్ నంబర్ నమోదు చేయండి',
    'login_otp_hint': 'మీ నంబర్ ధృవీకరణ కోసం OTP పంపిస్తాము',
    'or_continue_with': 'లేదా కొనసాగండి',
    'continue_with_google': 'Google తో కొనసాగండి',
    'choose_language_inline': 'భాష ఎంచుకోండి',
    'google_login_soon': 'Google లాగిన్ త్వరలో వస్తుంది.',
    'english': 'ఇంగ్లీష్',
    'telugu': 'తెలుగు',
    'request_completed': 'రిక్వెస్ట్ పూర్తైంది.',
    'guest': 'అతిథి',
    'done': 'పూర్తైంది',
    'profile_title': 'నా ప్రొఫైల్',
    'profile_customer_profile': 'కస్టమర్ ప్రొఫైల్',
    'profile_profile_details': 'ప్రొఫైల్ వివరాలు',
    'profile_saved_addresses': 'సేవ్ చేసిన చిరునామాలు',
    'profile_no_saved_addresses':
        'ఇంకా చిరునామాలు సేవ్ చేయలేదు. జోడించడానికి Add నొక్కండి.',
    'profile_address_fallback': 'చిరునామా',
    'profile_pin_prefix': 'పిన్',
    'profile_default': 'డిఫాల్ట్',
    'profile_name': 'పేరు',
    'profile_mobile': 'మొబైల్',
    'profile_village': 'గ్రామం',
    'profile_pincode': 'పిన్‌కోడ్',
    'profile_add': 'జోడించు',
    'profile_edit_profile': 'ప్రొఫైల్ సవరించు',
    'profile_delete': 'తొలగించు',
    'profile_cancel': 'రద్దు',
    'profile_update': 'అప్‌డేట్',
    'profile_add_address': 'చిరునామా జోడించు',
    'profile_delete_address': 'చిరునామా తొలగింపు',
    'profile_delete_confirm': 'ఈ చిరునామాను తొలగించాలా',
    'profile_updated_success': 'ప్రొఫైల్ విజయవంతంగా అప్‌డేట్ అయింది',
    'profile_address_added_success': 'చిరునామా విజయవంతంగా జోడించబడింది',
    'profile_address_deleted': 'చిరునామా తొలగించబడింది',
  };

  static String tr(AppLanguage language, String key) {
    final map = language == AppLanguage.te ? _te : _en;
    return map[key] ?? key;
  }
}
